"""empty message

Revision ID: 28a559c00b07
Revises: 2a566df4e19a
Create Date: 2022-03-22 20:03:47.357564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a559c00b07'
down_revision = '2a566df4e19a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('img', sa.Column('out', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('img', 'out')
    # ### end Alembic commands ###
