"""empty message

Revision ID: 2a566df4e19a
Revises: 959a4ab4e4c4
Create Date: 2022-03-22 19:51:13.728007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a566df4e19a'
down_revision = '959a4ab4e4c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('img', sa.Column('prediction', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('img', 'prediction')
    # ### end Alembic commands ###
